[package]
name                 = "caracal-metrics"
description          = "Caracal metrics utilities"
version.workspace    = true
authors.workspace    = true
homepage.workspace   = true
repository.workspace = true
readme.workspace     = true
license.workspace    = true
edition.workspace    = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
async-trait = "0.1"
tokio       = { version = "1", features = ["net"] }

axum       = "0.7"
tower      = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.5", features = ["trace"] }

bytes       = "1"
lazy_static = "1"
mime        = "0.3"
prometheus  = "0.13"
snafu       = "0.8"

[lints]
workspace = true
