edition           = "2021"
unstable_features = true

condense_wildcard_suffixes = true
fn_single_line             = true
format_macro_matchers      = true
format_strings             = true
group_imports              = "StdExternalCrate"
imports_granularity        = "Crate"
imports_layout             = "Mixed"
max_width                  = 100
newline_style              = "Unix"
normalize_comments         = true
normalize_doc_attributes   = true
reorder_impl_items         = true
reorder_imports            = true
trailing_comma             = "Vertical"
use_field_init_shorthand   = true
use_small_heuristics       = "Max"
use_try_shorthand          = true
wrap_comments              = true
