[default]
extend-ignore-identifiers-re = [
  # long base64 strings
  "[a-zA-Z0-9+/]{50,}",
]

[default.extend-words]
crate = "crate"
Crate = "Crate"

[files]
extend-exclude = ["target/", "Cargo.lock", "flake.lock"]
