name: Container

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - ci/*
    tags:
      - v*

env:
  CI: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SCCACHE_BUCKET: sccache

concurrency:
  group: image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build and publish images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - release
    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install docker-buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge
            type=raw,enable=${{ github.event_name != 'pull_request' && !contains(github.ref, 'refs/tags/') }},value=build-{{date 'YYYY.MM.DD'}}-{{sha}}
          flavor: |
            latest=auto
            suffix=${{ matrix.mode == 'debug' && '-debug' || ''}}
          bake-target: caracal

      - name: Build container image
        uses: docker/bake-action@v5
        with:
          pull: true
          push: true
          set: |
            caracal.args.AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            caracal.args.AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            caracal.args.SCCACHE_BUCKET=${{ env.SCCACHE_BUCKET }}
            caracal.args.SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
            caracal.args.SCCACHE_S3_USE_SSL=false

          files: |
            ./dev-support/containers/docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: caracal
